재수정

diff --git a/.github/workflows/e2e_test-push-another-repo.yaml b/.github/workflows/e2e_test-push-another-repo.yaml
--- a/.github/workflows/e2e_test-push-another-repo.yaml
+++ b/.github/workflows/e2e_test-push-another-repo.yaml
@@ -71,81 +71,83 @@ jobs:
           path: playwright-report/
           retention-days: 3
 
-      - name: Pushes to another repository
-        uses: cpina/github-action-push-to-another-repository@main
-        if: success() || failure()
+      # - name: Pushes to another repository
+      #   uses: cpina/github-action-push-to-another-repository@main
+      #   if: success() || failure()
+      #   env:
+      #     SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
+      #   with:
+      #     source-directory: "playwright-report"
+      #     destination-github-username: "lastrites2018"
+      #     destination-repository-name: "vos-test-report-frontend"
+      #     user-email: lastrites@nate.com
+      #     target-branch: gh-pages
+
+  publish_report:
+    name: Publish HTML Report
+    # using always() is not ideal here, because it would also run if the workflow was cancelled
+    if: success() || needs.dashboard_test.result == 'failure'
+    needs: [dashboard_test]
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    env:
+      # Unique URL path for each workflow run attempt
+      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
+    steps:
+      - name: Checkout GitHub Pages Branch
+        uses: actions/checkout@v3
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
         with:
-          source-directory: "playwright-report"
-          destination-github-username: "lastrites2018"
-          destination-repository-name: "vos-test-report-frontend"
-          user-email: lastrites@nate.com
-          target-branch: gh-pages
+          repository: lastrites2018/vos-test-report-frontend
+          ref: gh-pages
+      - name: Set Git User
+        # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+      - name: Download zipped HTML report
+        uses: actions/download-artifact@v3
+        with:
+          name: playwright-report
+          path: ${{ env.HTML_REPORT_URL_PATH }}
+      - name: Push HTML Report
+        timeout-minutes: 3
+        # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
+        # this is necessary when this job is running at least twice at the same time (e.g. through two pushes at the same time)
+        run: |
+          git add .
+          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }}) https://${{github.repository_owner}}.github.io/test-local-yaml/$HTML_REPORT_URL_PATH"
 
-  # publish_report:
-  #   name: Publish HTML Report
-  #   # using always() is not ideal here, because it would also run if the workflow was cancelled
-  #   if: success() || needs.dashboard_test.result == 'failure'
-  #   needs: [dashboard_test]
-  #   runs-on: ubuntu-latest
-  #   continue-on-error: true
-  #   env:
-  #     # Unique URL path for each workflow run attempt
-  #     HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
-  #   steps:
-  #     - name: Checkout GitHub Pages Branch
-  #       uses: actions/checkout@v3
-  #       with:
-  #         ref: gh-pages
-  #     - name: Set Git User
-  #       # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
-  #       run: |
-  #         git config --global user.name "github-actions[bot]"
-  #         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
-  #     - name: Download zipped HTML report
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: playwright-report
-  #         path: ${{ env.HTML_REPORT_URL_PATH }}
-  #     - name: Push HTML Report
-  #       timeout-minutes: 3
-  #       # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
-  #       # this is necessary when this job is running at least twice at the same time (e.g. through two pushes at the same time)
-  #       run: |
-  #         git add .
-  #         git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }}) https://${{github.repository_owner}}.github.io/test-local-yaml/$HTML_REPORT_URL_PATH"
+          while true; do
+            git pull --rebase
+            if [ $? -ne 0 ]; then
+              echo "Failed to rebase. Please review manually."
+              exit 1
+            fi
 
-  #         while true; do
-  #           git pull --rebase
-  #           if [ $? -ne 0 ]; then
-  #             echo "Failed to rebase. Please review manually."
-  #             exit 1
-  #           fi
+            git push
+            if [ $? -eq 0 ]; then
+              echo "Successfully pushed HTML report to repo."
+              exit 0
+            fi
+          done
 
-  #           git push
-  #           if [ $? -eq 0 ]; then
-  #             echo "Successfully pushed HTML report to repo."
-  #             exit 0
-  #           fi
-  #         done
+      - name: Output Report URL as Worfklow Annotation
+        id: full-html-report-url
+        run: |
+          FULL_HTML_REPORT_URL=https://${{github.repository_owner}}.github.io/test-local-yaml/$HTML_REPORT_URL_PATH
+          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
+          echo "::set-output name=full-html-report-url::$FULL_HTML_REPORT_URL"
 
-  #     - name: Output Report URL as Worfklow Annotation
-  #       id: full-html-report-url
-  #       run: |
-  #         FULL_HTML_REPORT_URL=https://${{github.repository_owner}}.github.io/test-local-yaml/$HTML_REPORT_URL_PATH
-  #         echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
-  #         echo "::set-output name=full-html-report-url::$FULL_HTML_REPORT_URL"
-
-  #   outputs:
-  #     full-html-report-url: ${{ steps.full-html-report-url.outputs.full-html-report-url}}
+    outputs:
+      full-html-report-url: ${{ steps.full-html-report-url.outputs.full-html-report-url}}
 
   slack_notification:
     name: slack notification (end)
     if: success() || needs.dashboard_test.result == 'failure'
     runs-on: ubuntu-latest
-    # needs: [dashboard_test, publish_report]
-    needs: [dashboard_test]
+    needs: [dashboard_test, publish_report]
     steps:
       - name: github checkout
         uses: actions/checkout@v3
